### ISSUE TITLE
Duplicate in Array problem set.

### ISSUE THREAD

**Issue by karthiikselvam** [jeffzh4ng/algorithms-and-data-structures#70]
![image](https://user-images.githubusercontent.com/35266917/99722477-b734f080-2ad6-11eb-8fc3-41d7138e8de5.png)

**Comment by jeffzh4ng** [comment]
Fixed in https://github.com/jeffzh4ng/algorithms-and-data-structures/commit/8754206739afdcbb9d2e69e0841ced11b536f0bd.
